print("                  _     _             ")
print("                 / \~~~/ \            ")
print("           ,----(   . .   )           ")
print("          /      \_     _/            ")
print("         /|        (\  |(             ")
print("        ^ \   /__\  /\ |              ")
print("           |__|  |__|-''              ")

print("                  _     _             ")
print("                 / \~~~/ \            ")
print("           ,----(   . .   )           ")
print("          /      \_     _/            ")
print("         /|        (\  |(             ")
print("        ^ \   /__\  /\ |              ")
print("           |__|  |__|-''              ")

